import 'package:flutter/material.dart';

List<Color> backgroundColorss = [
  Colors.white,
  Colors.grey,
  Colors.blue,
  Colors.green,
  Colors.red,
  Colors.yellow,
  Colors.purple,
  Colors.pink,
  Colors.orange,
  Colors.teal,
  Colors.cyan,
  Colors.indigo,
  Colors.brown,
  Colors.amber,
  Colors.lime,
  Colors.lightBlue,
  Colors.deepPurple,
  Colors.lightGreen,
  Colors.blueGrey,
  Colors.redAccent,
  Colors.pinkAccent,
  Colors.orangeAccent,
  Colors.yellowAccent,
  Colors.greenAccent,
  Colors.tealAccent,
  Colors.cyanAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.deepPurpleAccent,
  Colors.lightBlueAccent,
  Colors.lightGreenAccent,
];
